global:
  scrape_interval: 6s
  evaluation_interval: 6s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'api-gestao-vagas'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] 
        labels:
          application: 'api-gestao-vagas'